volumes:
  db-data:
  venv-data:

services:
  db:
    image: ghcr.io/kvdomingo/postgresql-pig:18
    pull_policy: weekly
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', '${DATABASE_USER}', '-d', '${DATABASE_NAME}' ]
      start_period: 10s
      retries: 3
      interval: 20s
      timeout: 2s

  migrations:
    image: ghcr.io/amacneil/dbmate:latest
    restart: no
    user: 1000:1000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DBMATE_MIGRATIONS_DIR: /app/repositories/sql/migrations
      DBMATE_SCHEMA_FILE: /app/repositories/sql/schema.sql
    working_dir: /app
    volumes:
      - ./api:/app
    profiles: [ admin ]
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: api
    image: ghcr.io/kvdomingo/resto-tracker-api
    pull_policy: weekly
    restart: unless-stopped
    environment:
      PYTHON_ENV: development
      PORT: 8000
      DATABASE_URL: ${DATABASE_URL}
    entrypoint:
      - /bin/bash
      - -euxo
      - pipefail
      - -c
    command:
      - >
        uv sync --all-groups --frozen;
        uv run fastapi dev --host 0.0.0.0 --reload;
    volumes:
      - ./api:/app
      - venv-data:/app/.venv
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./api/pyproject.toml
          action: restart
        - path: ./api/uv.lock
          action: restart

  ui:
    image: oven/bun:1
    restart: unless-stopped
    working_dir: /app
    environment:
      NODE_ENV: development
    entrypoint:
      - /bin/bash
      - -euxo
      - pipefail
      - -c
    command:
      - >
        bun install --frozen-lockfile;
        exec bun run dev;
    volumes:
      - ./ui:/app
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./ui/package.json
          action: restart
        - path: ./ui/bun.lock
          action: restart
