version: "3"

env:
  DBMATE_MIGRATIONS_DIR:
    sh: echo "$(pwd)/api/repositories/sql/migrations"
  DBMATE_SCHEMA_FILE:
    sh: echo "$(pwd)/api/repositories/sql/schema.sql"

tasks:
  default:
    cmd:
      task: up

  setup:
    desc: Initial setup
    ignore_error: true
    cmds:
      - pip install -U prek
      - prek install
      - uv sync --dev --all-groups

  up:
    desc: Run the development server
    interactive: true
    cmd: infisical run --watch -- docker compose up --build --watch --remove-orphans {{ .CLI_ARGS }}

  stop:
    desc: Stop containers
    cmd: docker compose stop {{ .CLI_ARGS }}

  logs:
    desc: Follow logs
    interactive: true
    cmd: docker compose logs --follow {{ .CLI_ARGS }}

  restart:
    desc: Restart containers
    cmd: docker compose restart {{ .CLI_ARGS }}

  down:
    desc: Stop and remove containers
    cmd: docker compose down {{ .CLI_ARGS }}

  clean:
    desc: Nuke everything
    cmd: docker compose down --volumes --remove-orphans {{ .CLI_ARGS }}

  exec:
    desc: Execute a command in a running container
    cmd: docker compose exec {{ .CLI_ARGS }}

  pgcli:
    desc: Connect to the db container via pgcli
    cmd: pgcli postgres://postgres:postgres@localhost:5432/postgres

  makemigrations:
    desc: Create a migration file
    cmd: infisical run -- dbmate new {{ .CLI_ARGS }}

  migrate:
    desc: Apply migrations
    cmd: infisical run -- docker compose --rm -it migrations dbmate up
