version: "3"

tasks:
  default:
    cmd:
      task: up

  setup:
    desc: Initial setup
    ignore_error: true
    cmds:
      - pip install -U prek
      - prek install
      - uv sync --dev --all-groups

  up:
    desc: Run the development server
    interactive: true
    cmd: >
      infisical run --watch --
      docker compose up --watch --remove-orphans {{ .CLI_ARGS }}

  stop:
    desc: Stop containers
    cmd: docker compose stop {{ .CLI_ARGS }}

  logs:
    desc: Follow logs
    interactive: true
    cmd: docker compose logs --follow {{ .CLI_ARGS }}

  restart:
    desc: Restart containers
    cmd: docker compose restart {{ .CLI_ARGS }}

  down:
    desc: Stop and remove containers
    cmd: docker compose down {{ .CLI_ARGS }}

  clean:
    desc: Nuke everything
    cmd: docker compose down --volumes --remove-orphans {{ .CLI_ARGS }}

  exec:
    desc: Execute a command in a running container
    cmd: docker compose exec {{ .CLI_ARGS }}

  pgcli:
    desc: Connect to the db container via pgcli
    interactive: true
    cmd: pgcli postgres://postgres:postgres@localhost:5432/postgres

  makemigrations:
    desc: Create a migration file
    cmd: infisical run -- dbmate new {{ .CLI_ARGS }}

  migrate:
    desc: Apply migrations
    cmd: infisical run -- docker compose run --rm -it migrations up

  unmigrate:
    desc: Rollback migration
    cmd: infisical run -- docker compose run --rm -it migrations down

  load-fixtures:
    desc: Load database fixtures
    cmd: |
      for f in api/repositories/sql/fixtures/*.sql; do
        echo "Loading $f"
        infisical run -- docker compose exec -T db \
          sh -c 'psql -v ON_ERROR_STOP=1 -U "$DATABASE_USER" -d "$DATABASE_NAME"' < "$f"
      done
