/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/restaurants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Restaurants */
    get: operations["list_restaurants_api_restaurants_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/restaurants/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Restaurant */
    get: operations["get_restaurant_api_restaurants__id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Coordinates */
    Coordinates: {
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** PaginatedMeta */
    PaginatedMeta: {
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Page Count */
      page_count: number;
      /** Total Count */
      total_count?: number | null;
    };
    /** Paginated[Restaurant] */
    Paginated_Restaurant_: {
      /** Data */
      data: components["schemas"]["Restaurant"][];
      meta: components["schemas"]["PaginatedMeta"];
    };
    /** Restaurant */
    Restaurant: {
      /** Id */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By Id */
      created_by_id: string | null;
      /** Name */
      name: string;
      /** Price Tier */
      price_tier: number;
      /** Tags */
      tags: string[];
      /** Branches */
      branches: components["schemas"]["RestaurantBranches"][];
      /** Instagram Handle */
      instagram_handle: string | null;
      /** Website */
      website: string | null;
      /** Menu Url */
      menu_url: string | null;
      /** Is Reservation Required */
      is_reservation_required: boolean | null;
    };
    /** RestaurantBranches */
    RestaurantBranches: {
      /** Location */
      location: string;
      geography?: components["schemas"]["Coordinates"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_restaurants_api_restaurants_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Paginated_Restaurant_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_restaurant_api_restaurants__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Restaurant"] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
