[project]
name = "resto-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kenneth V. Domingo", email = "hello@kvd.studio" }
]
requires-python = "~=3.14.0"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "loguru>=0.7.3",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "scalar-fastapi>=1.8.2",
    "sqlalchemy>=2.0.51",
    "stytch>=15.3.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.2",
    "ty>=0.0.69",
]

[tool.ruff]
target-version = "py313"
line-length = 88
exclude = ["repositories/generated"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends", "fastapi.Query", "fastapi.Path", "fastapi.Security"
]
